# Generated by Django 3.2.7 on 2021-10-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
